# Generated by Django 5.1.2 on 2024-11-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_geometry_region_polygon_location_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
