# Generated by Django 5.1.2 on 2024-11-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
    ]
