# Generated by Django 5.1.2 on 2024-11-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_post_location_post_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_url', models.URLField(help_text='URL to GIF or video that shows the map changes')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.location')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.region')),
            ],
        ),
    ]
