# Generated by Django 5.1.2 on 2024-11-25 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_mapchanges_location_alter_mapchanges_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchanges',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='List of image URLs showing the map changes', size=None),
        ),
        migrations.AlterField(
            model_name='mapchanges',
            name='animation_url',
            field=models.URLField(blank=True, help_text='URL to GIF or video that shows the map changes', null=True),
        ),
    ]
