# Generated by Django 5.1.2 on 2024-11-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_mapchanges_image_urls_alter_mapchanges_animation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapchanges',
            name='animation_url',
        ),
        migrations.RemoveField(
            model_name='mapchanges',
            name='image_urls',
        ),
        migrations.CreateModel(
            name='MapChangeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='map_changes/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('map_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.mapchanges')),
            ],
        ),
    ]
