# Generated by Django 5.1.2 on 2024-11-25 17:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_remove_mapchanges_animation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
