# Generated by Django 5.1.2 on 2024-11-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_location_geojson_region_geojson_alter_region_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchanges',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
